# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: w35
email: contact@wesaspinall.com
description: > # this means to ignore newlines until "baseurl:"
  Javascript, business & motivational literature, kung-fu, digital
  photography.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wesaspinall.com" # the base hostname & protocol for your site

profile_pic: https://avatars.githubusercontent.com/u/14037370?v=3

twitter_username: wesaspinall
github_username:  wesaspinall
github: wesaspinall
linkedin: true
linkedin_username: wesaspinall

disqus: wesaspinall
name: Wes Aspinall
gaaccount: true
comments: true


# Build settings
markdown: kramdown
theme: minima
permalink: pretty


